# Generated by Django 4.2.4 on 2023-09-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('calle', models.CharField(max_length=45)),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=150)),
                ('foto', models.CharField(max_length=500)),
                ('calificacion', models.IntegerField()),
                ('distancia_parada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=12)),
                ('numUnidad', models.IntegerField()),
                ('fechaCompra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('leagajo', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('habilitado', models.BooleanField()),
                ('detalles', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('calle', models.CharField(max_length=45)),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('foto', models.CharField(max_length=500)),
                ('atractivos', models.ManyToManyField(to='Bus.atractivo')),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('duracionAprox', models.IntegerField()),
                ('horaInicioAprox', models.DateTimeField()),
                ('horaFinalizacionAprox', models.DateTimeField()),
                ('frecuencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_viaje', models.IntegerField()),
                ('fecha', models.DateField()),
                ('inicio_real', models.TimeField()),
                ('final_real', models.TimeField()),
                ('inicio_estimado', models.TimeField()),
                ('final_estimado', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.bus')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.chofer')),
            ],
        ),
        migrations.CreateModel(
            name='ParadaxRecorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroParada', models.IntegerField()),
                ('llegadaEstimada', models.TimeField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.parada')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.recorrido')),
            ],
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCambio', models.DateTimeField(auto_now=True)),
                ('motivo', models.CharField(max_length=100)),
                ('estadoAnterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadoAnterior', to='Bus.estado')),
                ('estadoNuevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadoNuevo', to='Bus.estado')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.cambioestado'),
        ),
    ]
