# Generated by Django 4.2.4 on 2023-08-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=12)),
                ('numUnidad', models.IntegerField()),
                ('fechaCompra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCambio', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.bus')),
                ('estadoAnterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadoAnterior', to='Bus.estado')),
                ('estadoNuevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadoNuevo', to='Bus.estado')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.estado'),
        ),
    ]
