# Generated by Django 4.2.4 on 2023-09-08 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atractivo',
            name='distancia_parada',
        ),
        migrations.AlterField(
            model_name='atractivo',
            name='calificacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='duracionAprox',
            field=models.IntegerField(verbose_name='Duracion en minutos'),
        ),
    ]
