# Generated by Django 4.2.5 on 2023-10-20 11:52

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0002_remove_atractivo_distancia_parada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recorrido',
            old_name='color',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='recorrido',
            name='hex_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='parada',
            name='foto',
            field=models.FileField(upload_to='imagenes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
