# Generated by Django 4.2.5 on 2023-09-22 12:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0002_remove_atractivo_distancia_parada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
