# Generated by Django 4.2.5 on 2023-09-22 13:09

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0003_alter_recorrido_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorrido',
            name='color',
        ),
        migrations.AddField(
            model_name='recorrido',
            name='hex_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='parada',
            name='foto',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
