# Generated by Django 4.2.6 on 2023-10-09 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0004_remove_recorrido_color_recorrido_hex_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parada',
            name='foto',
            field=models.FileField(upload_to='imagenes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
