# Generated by Django 4.2.6 on 2023-10-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0005_recorrido_nombre_alter_parada_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrido',
            name='nombre',
            field=models.CharField(default='noname', max_length=50),
            preserve_default=False,
        ),
    ]
