# Generated by Django 4.2.6 on 2023-10-19 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0006_alter_recorrido_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atractivo',
            name='foto',
            field=models.FileField(upload_to='imagenes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
