# Generated by Django 4.2.6 on 2023-10-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0007_alter_atractivo_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chofer',
            old_name='leagajo',
            new_name='legajo',
        ),
    ]
