# Generated by Django 4.2.6 on 2023-10-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0008_rename_leagajo_chofer_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='recorrido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bus.recorrido'),
            preserve_default=False,
        ),
    ]
