# Generated by Django 4.2.6 on 2023-10-23 13:12

import Bus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0009_viaje_recorrido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='dni',
            field=models.CharField(max_length=8, validators=[Bus.models.validate_numeric]),
        ),
    ]
