# Generated by Django 4.2.6 on 2023-10-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0010_alter_chofer_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atractivo',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parada',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='final_real',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='inicio_real',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
