# Generated by Django 4.2.6 on 2023-11-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0013_alter_viaje_bus_alter_viaje_chofer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='nro_viaje',
            field=models.IntegerField(default=0),
        ),
    ]
