# Generated by Django 4.2.6 on 2023-11-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0014_alter_viaje_nro_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='nro_viaje',
            field=models.IntegerField(),
        ),
    ]
